<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Images\**" />
    <EmbeddedResource Remove="Images\**" />
    <None Remove="Images\**" />
    <Page Remove="Images\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="View\Images\imageacceuil.png" />
    <None Remove="View\Images\imagegestionvin.png" />
    <None Remove="View\Images\imagestatvin.png" />
    <None Remove="View\Images\logogm.png" />
    <None Remove="View\Images\vinblanc.png" />
    <None Remove="View\Images\vinrose.png" />
    <None Remove="View\Images\vinrouge.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.7" />
    <PackageReference Include="WPFBootstrapUI" Version="1.0.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="View\Images\imageacceuil.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\Images\imagegestionvin.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\Images\imagestatvin.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\Images\logogm.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\Images\logogmcomplet.png" />
    <Resource Include="View\Images\vinblanc.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\Images\vinrose.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="View\Images\vinrouge.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  
  </ItemGroup>

</Project>
